name: install_plugin
description: A flutter plugin for install apk for android; and using url to go to app store for iOS.
version: 2.1.0
homepage: https://github.com/hui-z/flutter_install_plugin

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.zaihui.installplugin
        pluginClass: InstallPlugin
      ios:
        pluginClass: InstallPlugin
